question_data = [
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "What does the term MIME stand for, in regards to computing?",
     "correct_answer": "Multipurpose Internet Mail Extensions",
     "incorrect_answers": ["Mail Internet Mail Exchange", "Multipurpose Interleave Mail Exchange",
                           "Mail Interleave Method Exchange"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "In the programming language &quot;Python&quot;, which of these statements "
                 "would display the string &quot;Hello World&quot; correctly?",
     "correct_answer": "print(&quot;Hello World&quot;)",
     "incorrect_answers": ["console.log(&quot;Hello World&quot;)", "echo &quot;Hello World&quot;",
                           "printf(&quot;Hello World&quot;)"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "Which programming language was developed by Sun Microsystems in 1995?", "correct_answer": "Java",
     "incorrect_answers": ["Python", "Solaris OS", "C++"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "What is the name of the default theme that is installed with Windows XP?", "correct_answer": "Luna",
     "incorrect_answers": ["Neptune", "Whistler", "Bliss"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "Which of these people was NOT a founder of Apple Inc?", "correct_answer": "Jonathan Ive",
     "incorrect_answers": ["Steve Jobs", "Ronald Wayne", "Steve Wozniak"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "On which day did the World Wide Web go online?", "correct_answer": "December 20, 1990",
     "incorrect_answers": ["December 17, 1996", "November 12, 1990", "November 24, 1995"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "In programming, what do you call functions with the same name but different implementations?",
     "correct_answer": "Overloading", "incorrect_answers": ["Overriding", "Abstracting", "Inheriting"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "In programming, the ternary operator is mostly defined with what symbol(s)?", "correct_answer": "?:",
     "incorrect_answers": ["??", "if then", "?"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": ".rs is the top-level domain for what country?", "correct_answer": "Serbia",
     "incorrect_answers": ["Romania", "Russia", "Rwanda"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "Unix Time is defined as the number of seconds that have elapsed since when?",
     "correct_answer": "Midnight, January 1, 1970",
     "incorrect_answers": ["Midnight, July 4, 1976", "Midnight on the creator of Unix&#039;s birthday",
                           "Midnight, July 4, 1980"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "Which of these programming languages is a low-level language?", "correct_answer": "Assembly",
     "incorrect_answers": ["Python", "C#", "Pascal"]},
    {"type": "multiple", "difficulty": "medium", "category": "Science: Computers",
     "question": "Whistler was the codename of this Microsoft Operating System.", "correct_answer": "Windows XP",
     "incorrect_answers": ["Windows 2000", "Windows 7", "Windows 95"]}]
